### ISSUE TITLE
Option -gg

### ISSUE THREAD

**Issue by Traveler4** [outflanknl/EvilClippy#24]
The documentation pretends that there is an option -gg to unhide code.
When one runs EvilClippy with -h, this option is not listed.

Please harmonise between documentation, -h and the actual implementation.

**Comment by clr2of8** [comment]
Hello Traveler4, the implementation does include a -gg option but currently, you would have to build the executable from the latest code as described in the README to have the option available to you. This is because the pre-built executable on the releases page was built before the -gg option was added. I have requested the maintainers to provide an updated executable on the releases page for the convenience of those who prefer not to build the executable themselves. Thank you.

**Comment by Traveler4** [comment]
Thank you for the clarifying and helping hint.

**Comment by Traveler4** [comment]
I have made a small improvement to evilclippy.cs. I would like to contribute it to the project, but are not able to upload. Who can help?

**Comment by stanhegt** [comment]
Thanks, all contributions are highly appreciated. Please submit it as a pull request. More information here: https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by Traveler4** [comment]
Thanks for pointing me in the right direction. Did a fork, did my edits, did send the pull request.

**Comment by stanhegt** [comment]
I've added a new binary release which includes this option: https://github.com/outflanknl/EvilClippy/releases/tag/v1.3
